export {
  useAddDocumentMutation,
  useAddFeedbackMutation,
  useEmployeeProfileActionItemsQuery,
  useEmployeeProfileAssignmentHistoryQuery,
  useEmployeeProfileDocumentsQuery,
  useEmployeeProfileFeedbacksQuery,
  useEmployeeProfileIdpQuery,
  useEmployeeProfilePersonQuery,
  useEmployeeProfileProjectHistoryQuery,
  useEmployeeProfileRisksQuery,
  useEmployeeProfileScheduledLeavesQuery,
  useEmployeeProfileSkillsQuery,
  useUpdateIdpMutation,
  useUpdatePersonMutation,
} from './use-employee-profile-hooks'
